name = "CanonicalTraits"
uuid = "a603d957-0e48-4f86-8fbd-0b7bc66df689"
authors = ["thautwarm"]
version = "0.1.0"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Polynomials", "LinearAlgebra"]
